###
POST http://localhost:9000/api/users  HTTP/1.1
Content-Type: application/json

{
  "mov_id": 901,
  "mov_title": "vertigo",
  "mov_year": 1958,
  "mov_time": 128,
  "mov_lang": "english",
  "mov_rel_country": "uk"
}

//-------- ------------------------MOVIES ------------------------------------------//
###
POST http://localhost:9000/api/movies  HTTP/1.1
Content-Type: application/json

{
  "mov_id": 901,
  "mov_title": "vertigo",
  "mov_year": 1958,
  "mov_time": 128,
  "mov_lang": "english",
  "mov_rel_country": "uk"
}

###
GET http://localhost:9000/api/movies  HTTP/1.1

###
GET http://localhost:9000/api/movies  HTTP/1.1

###
PUT http://localhost:9000/api/movies  HTTP/1.1
Content-Type: application/json

{
  "mov_id": 901,
  "mov_title": "vertigo",
  "mov_year": 19558,
  "mov_time": 128,
  "mov_lang": "english",
  "mov_rel_country": "uk"
}

###
DELETE  http://localhost:9000/api/movies  HTTP/1.1

//-------- ------------------------ACTOR ------------------------------------------//
###
POST http://localhost:9000/api/actor  HTTP/1.1
Content-Type: application/json

{
  "act_id": 101,
  "act_fname": "James",
  "act_lname": "Stewart",
  "act_gender": "M"
}
###
GET http://localhost:9000/api/actor  HTTP/1.1

###
GET http://localhost:9000/api/actor  HTTP/1.1

###
PUT http://localhost:9000/api/actor  HTTP/1.1
Content-Type: application/json

{
  "act_id": 101,
  "act_fname": "James",
  "act_lname": "Stewart",
  "act_gender": "M"
}
###
DELETE  http://localhost:9000/api/actor  HTTP/1.1

//-------- ------------------------MOVIECAST ------------------------------------------//
###
POST http://localhost:9000/api/moviecast  HTTP/1.1
Content-Type: application/json

{
  "act_id": 101,
  "mov_id": 901,
  "role": "John Scottie Ferguson"
}

###
GET http://localhost:9000/api/moviecast   HTTP/1.1

###
GET http://localhost:9000/api/moviecast  HTTP/1.1

###
PUT http://localhost:9000/api/moviecast  HTTP/1.1
Content-Type: application/json

{
  "act_id": 101,
  "mov_id": 901,
  "role": "John Scottie Ferguson"
}
###
DELETE  http://localhost:9000/api/moviecast  HTTP/1.1

//-------- ------------------------ GENRES ------------------------------------------//
###
POST http://localhost:9000/api/genres  HTTP/1.1
Content-Type: application/json

{
  "gen_id": 1001,
  "gen_title": "Action"
}

###
GET http://localhost:9000/api/genres   HTTP/1.1

###
GET http://localhost:9000/api/genres  HTTP/1.1

###
PUT http://localhost:9000/api/genres  HTTP/1.1
Content-Type: application/json

{
  "mov_id": 922,
  "gen_id": 1001
}
###
DELETE  http://localhost:9000/api/genres  HTTP/1.1

//-------- ------------------------ MOVIEGENRES ------------------------------------------//
###
POST http://localhost:9000/api/moviegenres  HTTP/1.1
Content-Type: application/json

{
  "mov_id": 922,
  "gen_id": 1001
}

###
GET http://localhost:9000/api/moviegenres   HTTP/1.1

###
GET http://localhost:9000/api/moviegenres  HTTP/1.1

###
PUT http://localhost:9000/api/moviegenres  HTTP/1.1
Content-Type: application/json

{
  "gen_id": 1001,
  "gen_title": "Action"
}
###
DELETE  http://localhost:9000/api/moviegenres  HTTP/1.1