###
POST http://localhost:9000/api/users  HTTP/1.1
Content-Type: application/json

{   
    "mov_id": 901,
    "mov_title": "vertigo",
    "mov_year": 1958,
    "mov_time": 128,
    "mov_lang": "english",
    "mov_rel_country": "uk"
}

###
POST http://localhost:9000/api/reviewers HTTP/1.1
Content-Type: application/json

{
    "rev_id": 1,
    "rev_name": "Righty Sock"
}
