###
POST http://localhost:9000/api/users  HTTP/1.1
Content-Type: application/json

{   
    "mov_id": 901,
    "mov_title": "vertigo",
    "mov_year": 1958,
    "mov_time": 128,
    "mov_lang": "english",
    "mov_rel_country": "uk"
}

//director
###
POST http://localhost:9000/api/director HTTP/1.1
Content-Type: application/json

{
    "dir_id": 201,
    "dir_fname": "Alfred",
    "dir_lname": "Hitchcock"
}

//reviewer
###
POST http://localhost:9000/api/reviewer/2 HTTP/1.1
Content-Type: application/json
{
    "rev_id": 2,
    "rev_name": "Righty Sock"
},


###
DELETE http://localhost:9000/api/reviewer HTTP/1.1
Content-Type: application/json

{
    "rev_id": 1,
    "rev_name": "Righty Sock"
}